/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSendDiagnosticoRouteImport } from './routes/api/public/send-diagnostico'

const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendDiagnosticoRoute =
  ApiPublicSendDiagnosticoRouteImport.update({
    id: '/api/public/send-diagnostico',
    path: '/api/public/send-diagnostico',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/api/public/send-diagnostico': typeof ApiPublicSendDiagnosticoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/api/public/send-diagnostico': typeof ApiPublicSendDiagnosticoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/api/public/send-diagnostico': typeof ApiPublicSendDiagnosticoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/diagnostico'
    | '/api/public/send-diagnostico'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/design-system' | '/diagnostico' | '/api/public/send-diagnostico'
  id:
    | '__root__'
    | '/'
    | '/design-system'
    | '/diagnostico'
    | '/api/public/send-diagnostico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignSystemRoute: typeof DesignSystemRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  ApiPublicSendDiagnosticoRoute: typeof ApiPublicSendDiagnosticoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-diagnostico': {
      id: '/api/public/send-diagnostico'
      path: '/api/public/send-diagnostico'
      fullPath: '/api/public/send-diagnostico'
      preLoaderRoute: typeof ApiPublicSendDiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignSystemRoute: DesignSystemRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  ApiPublicSendDiagnosticoRoute: ApiPublicSendDiagnosticoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
