/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSetupAdminsRouteImport } from './routes/api/public/setup-admins'
import { Route as ApiPublicSendDiagnosticoRouteImport } from './routes/api/public/send-diagnostico'

const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSetupAdminsRoute = ApiPublicSetupAdminsRouteImport.update({
  id: '/api/public/setup-admins',
  path: '/api/public/setup-admins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendDiagnosticoRoute =
  ApiPublicSendDiagnosticoRouteImport.update({
    id: '/api/public/send-diagnostico',
    path: '/api/public/send-diagnostico',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/design-system': typeof DesignSystemRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/api/public/send-diagnostico': typeof ApiPublicSendDiagnosticoRoute
  '/api/public/setup-admins': typeof ApiPublicSetupAdminsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/design-system': typeof DesignSystemRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/api/public/send-diagnostico': typeof ApiPublicSendDiagnosticoRoute
  '/api/public/setup-admins': typeof ApiPublicSetupAdminsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/design-system': typeof DesignSystemRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/api/public/send-diagnostico': typeof ApiPublicSendDiagnosticoRoute
  '/api/public/setup-admins': typeof ApiPublicSetupAdminsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/design-system'
    | '/diagnostico'
    | '/api/public/send-diagnostico'
    | '/api/public/setup-admins'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/design-system'
    | '/diagnostico'
    | '/api/public/send-diagnostico'
    | '/api/public/setup-admins'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/design-system'
    | '/diagnostico'
    | '/api/public/send-diagnostico'
    | '/api/public/setup-admins'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DesignSystemRoute: typeof DesignSystemRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  ApiPublicSendDiagnosticoRoute: typeof ApiPublicSendDiagnosticoRoute
  ApiPublicSetupAdminsRoute: typeof ApiPublicSetupAdminsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/setup-admins': {
      id: '/api/public/setup-admins'
      path: '/api/public/setup-admins'
      fullPath: '/api/public/setup-admins'
      preLoaderRoute: typeof ApiPublicSetupAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-diagnostico': {
      id: '/api/public/send-diagnostico'
      path: '/api/public/send-diagnostico'
      fullPath: '/api/public/send-diagnostico'
      preLoaderRoute: typeof ApiPublicSendDiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DesignSystemRoute: DesignSystemRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  ApiPublicSendDiagnosticoRoute: ApiPublicSendDiagnosticoRoute,
  ApiPublicSetupAdminsRoute: ApiPublicSetupAdminsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
